apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-postchat-widget-settings
spec:
  forms:
    - group: account
      label: 账户
      formSchema:
        - $formkit: text
          label: 账户KEY
          name: key
          id: key
          key: key
          value: "70b649f150276f289d1025508f60c5f58a"
          help: "使用PostChat的用户请前往 https://ai.tianli0.top/ 获取 KEY，只使用文章摘要的用户前往 https://summary.zhheo.com/ 获取 KEY 。示例的Key不支持文章摘要和自定义的知识库问答，但可以使用作者的知识库对话"
    - group: summary
      label: 文章摘要
      formSchema:
        - $formkit: checkbox
          label: 开启文章摘要
          name: enableSummary
          id: enableSummary
          key: enableSummary
          value: true
          help: "开启文章摘要需要在 https://summary.zhheo.com/ 绑定你的网站"
        - $formkit: text
          label: 文章选择器
          name: postSelector
          id: postSelector
          key: postSelector
          value: "article"
          help: "文章选择器，用于选择文章内容。如果没有正常显示摘要，你需要访问 https://postsummary.zhheo.com/theme/custom.html#%E8%8E%B7%E5%8F%96tianligpt-postselector 学习获取，也可以联系 zhheo@qq.com 发送你的网站地址后获取"
        - $formkit: text
          label: 摘要标题
          name: title
          id: title
          key: title
          value: "文章摘要"
          help: "摘要标题，用于显示在摘要顶部的自定义内容"
        - $formkit: attachment
          label: 摘要样式css
          name: summaryStyle
          id: summaryStyle
          key: summaryStyle
          value: "https://ai.tianli0.top/static/public/postChatUser_summary.min.css"
          help: "摘要样式css地址，如果你需要自定义摘要的css样式，可以自行修改。"
        - $formkit: text
          label: 文章路由
          name: postURL
          id: postURL
          key: postURL
          value: "*/archives/*"
          help: "在符合url条件的网页执行文章摘要功能，通常清况下，绝大多数Halo网站使用默认配置即可，无需调整"
        - $formkit: attachment
          label: 黑名单
          name: blacklist
          id: blacklist
          key: blacklist
          value: ""
          help: 填写相关的json地址，帮助文档：https://postsummary.zhheo.com/parameters.html#tianligpt-blacklist
        - $formkit: text
          label: 字数限制
          name: wordLimit
          id: wordLimit
          key: wordLimit
          value: "1000"
          help: 危险操作！如果没有在文章摘要中开启url绑定，更改此变量损失已消耗过的key，因为你提交的内容发生了变化。（PostChat用户无影响，因为摘要数量是无限的）可以设置提交的字数限制，默认为1000字。，帮助文档：https://postsummary.zhheo.com/parameters.html#tianligpt-wordlimit
        - $formkit: checkbox
          label: 打字动画效果
          name: typingAnimate
          id: typingAnimate
          key: typingAnimate
          value: true
          help: "智能的打字效果，模拟流处理的感觉"
        - $formkit: text
          label: 自定义开头语
          name: beginningText
          id: beginningText
          key: beginningText
          value: "这篇文章介绍了"
          help: "默认为“这篇文章介绍了”，你可以自定义开头语。"
        - $formkit: text
          label: 摘要主题
          name: summaryTheme
          id: summaryTheme
          key: summaryTheme
          value: "default"
          help: "切换文章摘要主题，详情请见 https://postchat.zhheo.com/theme.html"
    - group: chat
      label: 智能对话
      formSchema:
        - $formkit: checkbox
          label: 开启PostChat智能对话
          name: enableAI
          id: enableAI
          key: enableAI
          value: true
          help: "添加按钮点击对话的功能，如果你并非PostChat用户，而是仅文章摘要用户，建议关闭此功能"
        - $formkit: color
          label: 背景颜色
          name: backgroundColor
          id: backgroundColor
          key: backgroundColor
          value: "#3e86f6"
          help: "调整按钮背景色彩"
        - $formkit: color
          label: 填充颜色
          name: fill
          id: fill
          key: fill
          value: "#FFFFFF"
          help: "调整按钮里面图标的颜色"
        - $formkit: text
          label: 底部距离
          name: bottom
          id: bottom
          key: bottom
          value: "16px"
          help: "按钮距离底部的边距"
        - $formkit: text
          label: 左边距离
          name: left
          id: left
          key: left
          value: "16px"
          help: "按钮距离左侧的边距，如果填写负值，则是距离右侧的边距。例如left为-3px，实际为right 3px"
        - $formkit: text
          label: 宽度
          name: width
          id: width
          key: width
          value: "44px"
          help: "调整按钮的宽度"
        - $formkit: text
          label: 框架宽度
          name: frameWidth
          id: frameWidth
          key: frameWidth
          value: "375px"
          help: "调整聊天界面框架的宽度"
        - $formkit: text
          label: 框架高度
          name: frameHeight
          id: frameHeight
          key: frameHeight
          value: "600px"
          help: "调整聊天界面框架的高度"
        - $formkit: checkbox
          label: 默认输入
          name: defaultInput
          id: defaultInput
          key: defaultInput
          value: true
          help: "勾选此项时，用户点击按钮后会自动添加本页面标题，让用户更方便的询问关于本页的内容"
        - $formkit: checkbox
          label: 上传网站
          name: upLoadWeb
          id: upLoadWeb
          key: upLoadWeb
          value: true
          help: "勾选此项时，你的网站内容将会被自动提交到PostChat，用户知识库建立和搜索功能"
        - $formkit: checkbox
          label: 显示邀请链接
          name: showInviteLink
          id: showInviteLink
          key: showInviteLink
          value: true
          help: "勾选此项时，用户点击PostChat图标将访问你的邀请链接，被邀请用户在注册一年内开通的所有会员你会获得时长奖励。"
        - $formkit: text
          label: 界面标题
          name: userTitle
          id: userTitle
          key: userTitle
          value: "PostChat"
          help: "你要自定义的PostChat界面标题"
        - $formkit: text
          label: 聊天界面描述
          name: userDesc
          id: userDesc
          key: userDesc
          value: "如果你对网站的内容有任何疑问，可以来问我哦～"
          help: "你要自定义的PostChat聊天界面描述"
        - $formkit: checkbox
          label: 是否显示按钮
          name: addButton
          id: addButton
          key: addButton
          value: true
          help: "勾选此项时按钮会被显示。如果你是主题开发者在你自己通过主题开发添加按钮的情况时，建议将前面编辑按钮的参数设置得与你自己创造的按钮的参数相同，以便更好的计算窗口宽高和位置。如果主题开发者期望自行配置，可以用css的!important对内置样式进行覆盖。"